#pragma once

enum UpdateState
{
    UPDATE_CAMERA_POS,
    UPDATE_LIGHT_POS,
    UPDATE_TRANSFORM_HEAD,
    UPDATE_TRANSFORM_TORSO,
    UPDATE_TRANSFORM_LEFTARM,
    UPDATE_TRANSFORM_LEFTLOWERARM,
    UPDATE_TRANSFORM_RIGHTARM,
    UPDATE_TRANSFORM_RIGHTLOWERARM,
    UPDATE_TRANSFORM_LEFTLEG,
    UPDATE_TRANSFORM_LEFTLOWERLEG,
    UPDATE_TRANSFORM_RIGHTLEG,
    UPDATE_TRANSFORM_RIGHTLOWERLEG,
};
